#                           #
#   AutoSmelt by: tweedjt   #
#                           #

#Is AutoSmelt on by default
auto_smelt: false

#Are Drops to Inventory on by default
auto_pickup: true

#Drop exp orbs?
exp_drops: true

#Enable Fortune Drops for Fortune Pick?
fortune_drops: true

#Set the experience orb value for Iron
iron_exp: 1

#Set the experience orb value for Gold
gold_exp: 1

#Set the experience orb value for Netherite Scrap
nether_scrap_exp: 2

#On message for /as command
autosmelt_on_message: AutoSmelt has been turned &aON

#Off message for /as command
autosmelt_off_message: AutoSmelt has been turned &aOFF

#Message prefix for plugin
message_prefix: "&d[&fAutoSmelt&d] &r"